# Generated by Django 4.1.1 on 2023-07-14 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
